import type { Metadata } from "next";
import { Work_Sans,Crete_Round } from "next/font/google"; // Google Fonts shriftlarini import qilish
import "./globals.css";
import { ChildProps } from "@/types";
import { ThemeProvider } from "./(root)/_components/providers/themes-providers";

const creteRound = Crete_Round({
  weight: ["400"],
  subsets: ["latin"],
  variable: '--font-creteRound',
});

const workSans = Work_Sans({
  weight: ["500", "600"],
  subsets: ['latin'],
  variable: '--font-workSans',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}:ChildProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${creteRound.variable} ${workSans.variable} overflow-x-hidden`} // Bu yerda bo'shliq qo'shildi
      >
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange>  {children}</ThemeProvider>
      
      </body>
    </html>
  );
}
